### PR TITLE
Fix GraphQL query arguments for entries

### LINKED ISSUE #38: Graphql filters isOngoing, isPast, [...], and isFuture are failing in Craft CMS 5
the v5 redme states that the following query should be doable:

```gql
query{
  entries(
   section: "events",
   isFuture: ["dateRangeFieldHandle", true]
  ) {
    title
    ... on events_events_Entry {
      dateRangeFieldHandle {
        start
        end @formatDateTime(format: "d M Y")
        isPast
        isOnGoing
        isFuture
      }
    }
  }
}
```

Unfortunately this is not working in Craft CMS v5.5.3 erroring with:

```bash
Too few arguments to function studioespresso\\daterange\\behaviors\\EntryQueryBehavior::isFuture(), 1 passed and at least 2 expected"
```

trying to add the `entryTypeHandle` (same as described here `{% set events = craft.entries.section('events').isFuture('dateRangeFieldHandle', 'entryTypeHandle')  %}
`) is not having any affect resulting in the same error as ebove

ex: 
```gql
query{
  entries(
   section: "events",
   isFuture: ["dateRangeFieldHandle", "entryTypehandle", true]
  ) {
    title
    ... on events_events_Entry {
      dateRangeFieldHandle {
        start
        end @formatDateTime(format: "d M Y")
        isPast
        isOnGoing
        isFuture
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by yoannisj**
This PR addresses some issues with the GraphQL API.

1. Fix [error thrown](https://github.com/studioespresso/craft-date-range/issues/38) when querying entries based on a Date Range field, via the following Query argument methods:
- studioespresso\daterange\behaviors\EntryQueryBehaviour::isFuture()`
- studioespresso\daterange\behaviors\EntryQueryBehaviour::isPast()`
- studioespresso\daterange\behaviors\EntryQueryBehaviour::isNotPast()`
- studioespresso\daterange\behaviors\EntryQueryBehaviour::isOngoing()`

When used in a GraphQL query, only 1 array argument is given to those methods, which was thowing an error in the Craft v5 version because the methods require 2 arguments (date range field `handle` and `entryTypeHandle`). This PR fixes this by making the 2nd argument optional, and extracts it from the 1st array argument instead. Fixes #38

2. Fix typo in the `isOngoing` field on the GraphQL data type returned for Date Range fields.

---

Note: We are using our fork with the fixes above on one of our projects, and so far it is working well :).

### CODE REVIEW

**Comment by janhenckens** [comment]
Thanks for this @yoannisj! Haven't been able to spend much time on this plugin for the Craft 5 release as we don't regularly use it at the office. 

The PR looks good, I'll merge it and tag a new release - if you'd like you can then switch back to this version and test if it works the same in your project?

**Comment by janhenckens** [comment]
5.0.0-beta.3 is out with this fix!
